### ISSUE TITLE
raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by fanconic** [Anakeyn/Tensorflow2.0ForOldComputers#1]
Hi,
I recently tried to install your version of TF.
However, when I arrive at the point of installing the WHL file, I get the following error.
Am I missing something?

Let me know if there are any details I could provide you with to solve this issue!
Thank you!

```(venv) root@server:~/tmp/tsf# pip3 install tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
Processing ./tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 278, in unpack_url
    return unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 251, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 252, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/root/dermAI/venv/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by AdamMiltonBarker** [comment]
Follow the link directly and download the wheel then install it will work.

**Comment by Anakeyn** [comment]
Don't know why he said this is not a zip file ????  Did you follow the instructions ?  https://github.com/Anakeyn/Tensorflow2.0ForOldComputers

**Comment by AdamMiltonBarker** [comment]
> Don't know why he said this is not a zip file ???? Did you follow the instructions ? https://github.com/Anakeyn/Tensorflow2.0ForOldComputers

I got exactly the same error. Resolved it by downloading the file manually.
